# Generated by Django 4.2.30 on 2026-09-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('sector', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(default='TG', max_length=2)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('legal_id', models.CharField(blank=True, default='', max_length=80)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'organisation',
                'verbose_name_plural': 'organisations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='accounts.organization'),
        ),
    ]
