version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: monexa_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: monexa
      POSTGRES_USER: monexa
      POSTGRES_PASSWORD: monexa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monexa"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: monexa_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: change-me-in-production-please-use-a-long-random-string
      DEBUG: "False"
      ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://monexa:monexa@db:5432/monexa
      CORS_ALLOWED_ORIGINS: http://localhost:8080,http://127.0.0.1:8080
      LANGUAGE_CODE: fr
      TIME_ZONE: Africa/Lome
    ports:
      - "8000:8000"
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles

volumes:
  postgres_data:
  media_data:
  static_data:
