# Generated by Django 4.2.30 on 2026-09-25 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(default=7, unique=True)),
                ('forecast_data', models.JSONField(default=list)),
                ('confidence_low', models.JSONField(default=list)),
                ('confidence_high', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache prévision',
                'verbose_name_plural': 'Caches prévisions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=200, verbose_name='Client')),
                ('client_phone', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('RECONCILIE', 'Réconcilié'), ('ANOMALIE', 'Anomalie'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200, verbose_name='Fournisseur / Bénéficiaire')),
                ('category', models.CharField(choices=[('LOYER', 'Loyer'), ('SALAIRES', 'Salaires'), ('FOURNISSEURS', 'Fournisseurs'), ('TRANSPORT', 'Transport'), ('FOURNITURES', 'Fournitures'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('paid_at', models.DateTimeField(db_index=True, verbose_name='Date de paiement')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/%Y/%m/', verbose_name='Justificatif')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('channel', models.CharField(choices=[('TMONEY', 'T-Money'), ('MOOV', 'Moov Money'), ('FLOOZ', 'Flooz'), ('BANQUE', 'Banque'), ('ESPECES', 'Espèces')], db_index=True, max_length=20, verbose_name='Canal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Compte de trésorerie',
                'verbose_name_plural': 'Comptes de trésorerie',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_ref', models.CharField(db_index=True, help_text='Référence unique de la transaction Mobile Money.', max_length=50, unique=True, verbose_name='Référence opérateur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('channel', models.CharField(choices=[('TMONEY', 'T-Money'), ('MOOV', 'Moov Money'), ('FLOOZ', 'Flooz'), ('BANQUE', 'Banque'), ('ESPECES', 'Espèces')], db_index=True, max_length=20, verbose_name='Canal')),
                ('payer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Payeur')),
                ('payer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone payeur')),
                ('paid_at', models.DateTimeField(db_index=True, verbose_name='Date de paiement')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='evidence/%Y/%m/', verbose_name='Image de preuve')),
                ('raw_text', models.TextField(blank=True, default='', verbose_name="Texte brut extrait par l'IA")),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='Score de confiance IA (0-1)')),
                ('match_method', models.CharField(choices=[('AUTO_REF', 'Référence exacte'), ('AUTO_MONTANT', 'Montant + 7 jours'), ('FUZZY', 'Fuzzy nom/téléphone'), ('MANUEL', 'Validation manuelle'), ('IA', 'IA')], default='MANUEL', max_length=20, verbose_name='Méthode de matching')),
                ('status', models.CharField(choices=[('NON_RATTACHE', 'Non rattaché'), ('A_VALIDER', 'À valider'), ('RECONCILIE', 'Réconcilié'), ('ANOMALIE', 'Anomalie')], db_index=True, default='NON_RATTACHE', max_length=20, verbose_name='Statut')),
                ('anomaly_score', models.FloatField(default=0.0, verbose_name="Score d'anomalie (0-1)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice', verbose_name='Facture rapprochée')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['status', 'paid_at'], name='finance_pay_status_82bdf3_idx'), models.Index(fields=['channel', 'paid_at'], name='finance_pay_channel_7770a0_idx'), models.Index(fields=['anomaly_score'], name='finance_pay_anomaly_11f296_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issue_date'], name='finance_inv_status_7e531e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client_phone'], name='finance_inv_client__38f218_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'channel')},
        ),
    ]
