# Generated by Django 4.2.30 on 2026-09-25 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('connector_kind', models.CharField(choices=[('TMONEY', 'T-Money'), ('MOOV', 'Moov Money'), ('FLOOZ', 'Flooz'), ('BANQUE', 'Banque'), ('ESPECES', 'Caisse'), ('CSV', 'CSV / Excel'), ('SMS', 'SMS'), ('MANUAL', 'Saisie manuelle')], max_length=20)),
                ('integration_method', models.CharField(choices=[('SIMULATED_API', 'Connecteur simulé (aucune API opérateur réelle)'), ('CSV', 'Import CSV / Excel'), ('SMS', 'Preuve SMS'), ('PHOTO', 'Photo / capture'), ('MANUAL', 'Saisie manuelle')], default='SIMULATED_API', max_length=20)),
                ('channel', models.CharField(choices=[('TMONEY', 'T-Money'), ('MOOV', 'Moov Money'), ('FLOOZ', 'Flooz'), ('BANQUE', 'Banque'), ('ESPECES', 'Espèces')], db_index=True, max_length=20)),
                ('is_simulated', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('IDLE', 'En attente'), ('ERROR', 'Erreur'), ('DISABLED', 'Désactivé')], default='IDLE', max_length=20)),
                ('merchant_mask', models.CharField(blank=True, default='', max_length=32)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('cursor', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='finance.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Source financière',
                'verbose_name_plural': 'Sources financières',
                'ordering': ['channel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('PARTIAL', 'Partiel'), ('ERROR', 'Erreur')], default='RUNNING', max_length=20)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('ignored_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('cursor_before', models.CharField(blank=True, default='', max_length=120)),
                ('cursor_after', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='finance.financialsource')),
            ],
            options={
                'verbose_name': 'Synchronisation connecteur',
                'verbose_name_plural': 'Synchronisations connecteur',
                'ordering': ['-started_at'],
            },
        ),
    ]
