# Generated by Django 4.2.30 on 2026-09-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_tenancy'),
        ('finance', '0002_financial_sources'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='expense',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='financialsource',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_sources', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='forecastcache',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_caches', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='forecastcache',
            name='days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(db_index=True, help_text='Référence unique de la transaction Mobile Money (par organisation).', max_length=50, verbose_name='Référence opérateur'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('organization', 'name', 'channel')},
        ),
        migrations.AddConstraint(
            model_name='forecastcache',
            constraint=models.UniqueConstraint(fields=('organization', 'days'), name='uniq_forecast_days_per_org'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='uniq_invoice_ref_per_org'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('organization', 'provider_ref'), name='uniq_payment_ref_per_org'),
        ),
    ]
