# Generated by Django 4.2.30 on 2026-09-25 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('entity', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('prev_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', help_text="SHA-256 du hash de l'entrée précédente (zéros pour la première).", max_length=64)),
                ('hash', models.CharField(db_index=True, help_text='SHA-256 des propres données + prev_hash.', max_length=64, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BrokenChainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('expected_hash', models.CharField(max_length=64)),
                ('actual_hash', models.CharField(max_length=64)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_chain', to='auditing.auditlog')),
            ],
            options={
                'verbose_name': 'Cassure de chaîne',
                'verbose_name_plural': 'Cassures de chaîne',
            },
        ),
    ]
